[package]
name = "blobstream_sn"
version = "0.1.0"

[scripts]
test = "snforge test"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.19.0" }
starknet = ">=2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "f22438c" }
alexandria_bytes = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "c1a604e" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "c1a604e" }
succinct_sn = { git = "https://github.com/keep-starknet-strange/succinct-starknet.git", rev = "7890c7b" }

[[target.starknet-contract]]
casm = true
sierra = true
build-external-contracts = [
    "succinct_sn::fee_vault::succinct_fee_vault",
    "succinct_sn::gateway::succinct_gateway",
    "succinct_sn::mocks::erc20_mock::SnakeERC20Mock",
]

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true



