[book]
authors = ["drspacemn"]
language = "en"
multilingual = false
src = "src"
title = "Blobstream Starknet"

[output.html]
git-repository-url = "https://github.com/keep-starknet-strange/blobstream-starknet"
edit-url-template = "https://github.com/keep-starknet-strange/blobstream-starknet/issues/new/choose"
cname = "blobstream-stark.net"
