name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: asdf-vm/actions/install@v3
      
      - run: scarb fmt --check
      
      - name: build with scarb
        run: scarb build
        
      - name: build bindings with cargo
        run: cd bindings ; cargo build
        
      - name: test bindings
        run: snforge test
